# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14DNeKmtKiFhSpSOjg8zAHv831gzISIMk
"""

from flask import Flask, render_template, request, jsonify
from pyngrok import ngrok , conf
import joblib
import numpy as np

app = Flask(__name__, static_folder="static")

# Load the trained model (adjust the filename as needed)
model = joblib.load("/content/xgboost_pipeline.pkl")

@app.route("/")
def home():
    return render_template("index.html")

@app.route("/predict", methods=["POST"])
def predict():
    try:
        sex = int(request.form["sex"])
        fbs = int(request.form["fbs"])
        exang = int(request.form["exang"])
        restecg = int(request.form["restecg"])
        thal = int(request.form["thal"])
        cp = int(request.form["cp"])
        slope = int(request.form["slope"])

        features = np.array([[sex, fbs, exang, restecg, thal, cp, slope]])
        prediction = model.predict(features)[0]

        result = "High Risk" if prediction == 1 else "Low Risk"
        return jsonify({"result": result})
    except Exception as e:
        return jsonify({"error": str(e)})

# Run the app using ngrok
if __name__ == "__main__":
    conf.get_default().auth_token = "30gdo5ss2DkKWTsRipxkeLdM0Vw_5rvBGdDT2Qv4Y2Sf1EC4g"
    public_url = ngrok.connect(5000)
    print(" * ngrok tunnel:", public_url)
    app.run()